---

# Update PHP settings
#
- name: set php.ini date/timezone
  ini_file:
    dest=/etc/php.ini
    section=Date
    option=date.timezone
    value="Europe/London"
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server
    - php

- name: set php.ini max_execution_time
  ini_file:
    dest=/etc/php.ini
    section=PHP
    option=max_execution_time
    value=600
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server
    - php

- name: set php.ini max_input_type
  ini_file:
    dest=/etc/php.ini
    section=PHP
    option=max_input_time
    value=600
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server
    - php

- name: set php.ini post_max_size
  ini_file:
    dest=/etc/php.ini
    section=PHP
    option=post_max_size
    value=16M
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server
    - php

- name: set php.ini upload_max_filesize
  ini_file:
    dest=/etc/php.ini
    section=PHP
    option=upload_max_filesize
    value=16M
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server
    - php

- name: set php.ini disable_functions
  ini_file:
    dest=/etc/php.ini
    section=PHP
    option=disable_functions
    value=phpinfo
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server
    - php

- name: set php.ini expose_php
  ini_file:
    dest=/etc/php.ini
    section=PHP
    option=expose_php
    value=Off
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server
    - php

# Install Zabbix PHP config
#
- name: update web config
  template:
    src=web/zabbix.conf.php
    dest=/etc/zabbix/web/zabbix.conf.php
    mode=0644
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server

- name: restrict permissions of /etc/zabbix/web/zabbix.conf.php
  file: path=/etc/zabbix/web/zabbix.conf.php state=file mode=0440 owner=apache group=apache
  tags:
    - zabbix
    - zabbix-server


# Add /zabbix alias for apache
#
- name: apache config file
  template:
    src=zabbix_httpd.conf
    dest=/etc/httpd/conf.d/zabbix.conf
  notify: restart apache
  tags:
    - zabbix
    - zabbix-server

# And make sure Apache is restarted
#
# we set a flag file in /var/tmp to validate if this is the
# first time we execute this playbook.
#
- name: set flag for apache-php
  stat: path=/var/tmp/flag_zabbix-server-apache-php_end_of_first_run
  register: _apache_php_end_of_first_run

- name: enable and start Apache
  service: name=httpd state=restarted enabled=yes
  when: _apache_php_end_of_first_run.stat.exists == false
  tags:
    - zabbix
    - zabbix-server

- name: set flag to prevent an apache restart on next boot
  file: path=/var/tmp/flag_zabbix-server-apache-php_end_of_first_run
    state=touch
