

- name: Install pre-reqs for ansible
  pip: name={{ item }}
    state=present
    executable=/usr/local/bin/pip2.7
  with_items:
    - paramiko
    - PyYAML
    - Jinja2
    - httplib2
  tags:
    - ansible


- name: install ansible
  pip: name=ansible
    state=present
    version=1.6.2
    executable=/usr/local/bin/pip2.7
  tags:
  - ansible