- name: install development packages
  yum: name="{{ item }}" state=present
  with_items:
    - "@Development tools"
    - python-devel
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - gdbm-devel
    - db4-devel
    - libpcap-devel
    - xz-devel