---

- name: Ensure Jenkins Yum repo present
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
           dest=/etc/yum.repos.d/jenkins.repo mode=0644

- name: Check for Jenkins GPG in rpmdb
  command: rpm -q {{ jenkins_key }}
  register: keycheck
  ignore_errors: true

- name: Ensure Jenkins GPG key installed
  command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  when: keycheck|failed

